'use client';

import Header from '../components/organisms/Header';
import { CacheProvider } from '@chakra-ui/next-js';
import { ChakraProvider } from '@chakra-ui/react';
import { MyAccountProvider } from '../hooks/MyAccountContext'
import "../styles/globals.css"
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head>
        <title>Social events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <main>
          <CacheProvider>
            <ChakraProvider>
              <MyAccountProvider>
                {children}
              </MyAccountProvider>
            </ChakraProvider>
          </CacheProvider>
        </main>
      </body>
    </html>
  );
}
